[package]
name = "pathfinder"
version = "0.3.1"
authors = ["pontus"]
include = ["src/**/*", "Cargo.toml"]
description = "A small library to create nodes, groups of nodes and connection in between them utilizing the image crate."
repository = "https://github.com/pontuslae/pathfinder"
readme = "README.md"
keywords = ["nodes", "image"]
categories = ["visualization", "text-processing"]
license = "GPL-3.0"

[dependencies]
rand = "0.3"
image = "0.18"
gif = "0.9.2"
